
spring:
  data:
    rest:
      # Restful API Â·¾¶Ç°×º
      base-path: /api
      max-page-size: 10
      default-page-size: 5
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&tinyInt1isBit=false
    username: root
    password: abc123
  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  jackson:
    time-zone: GMT+8
logging:
  level:
    web: debug